# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='roomid',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
