# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatpool',
            name='roomname',
        ),
        migrations.RemoveField(
            model_name='roomaccount',
            name='roomname',
        ),
        migrations.RemoveField(
            model_name='roomaccount',
            name='username',
        ),
        migrations.DeleteModel(
            name='ChatPool',
        ),
        migrations.DeleteModel(
            name='RoomAccount',
        ),
    ]
